version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dx_local_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dx_project
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db_data:
